<?php

/**
 * PWA (Progressive Web App) Configuration — the package's template
 *
 * Copy this file to app/pwa/config.php in your project to use it; make:pwa
 * reads app/pwa/config.php and never this copy.
 *
 * Read by `./sfphp make:pwa`, which writes public/manifest.json and
 * public/service-worker.js from it. Nothing reads this file at request time,
 * so a change here reaches the browser only after make:pwa runs again. Flags
 * passed to make:pwa (--name, --short, --description, --color, --background,
 * --enable-push, --enable-sync) override the values below for that run.
 *
 * Values come from .env through Config::get(), the framework's own reader.
 */

use SfphpProject\src\Config;

$appName = Config::get('APP_NAME', 'SFPHP Application');
$appDescription = Config::get('APP_DESCRIPTION', '');

return [
    /**
     * App Name
     * Displayed in app stores and OS menus
     */
    'name' => $appName,

    /**
     * Short Name
     * Used when space is limited (up to 12 characters)
     */
    'short_name' => mb_substr($appName, 0, 12),

    /**
     * Description
     * Describes your app purpose
     */
    'description' => $appDescription,

    /**
     * Start URL
     * Where the app opens when installed
     */
    'start_url' => '/',

    /**
     * Scope
     * Which URLs are considered part of the app
     */
    'scope' => '/',

    /**
     * Display Mode
     * Options: 'fullscreen', 'standalone', 'minimal-ui', 'browser'
     */
    'display' => 'standalone',

    /**
     * Theme Color
     * Used in browser UI and app themes
     */
    'theme_color' => '#007AFF',

    /**
     * Background Color
     * Shown while app loads
     */
    'background_color' => '#ffffff',

    /**
     * Orientation
     * Default: 'portrait-primary'
     */
    'orientation' => 'portrait-primary',

    /**
     * Service Worker Settings
     */
    'service_worker' => [
        /**
         * Cache version
         * The cache is named "<app-name-slug>-<version>". Change it and run
         * make:pwa again: the new service worker deletes every other cache
         * when it activates.
         */
        'version' => 'v1',

        /**
         * Static Assets to Precache
         * Downloaded when the service worker installs. Any GET whose path ends
         * in a static extension (.css, .js, .png, .woff2, ...) is served
         * cache-first whether or not it is listed here; listing it only makes
         * it available offline before the first visit.
         * Avoid listing HTML pages in apps with login: they would be cached
         * with one user's content in them.
         */
        'static_assets' => [
            '/assets/css/sfcss.min.css',
            '/assets/js/sfjs.min.js',
            '/offline.html',
        ],

        /**
         * API Routes
         * Path patterns ('*' is a wildcard) that are always fetched from the
         * network and never cached, so private data never reaches the cache.
         */
        'api_routes' => [],

        /**
         * Offline Fallback Page
         * Shown when no connection and page not cached
         */
        'offline_fallback' => '/offline.html',

        /**
         * Enable Push Notifications
         */
        'enable_push_notifications' => false,

        /**
         * Enable Background Sync
         * Adds a 'sync' handler for the "sync-data" tag. It does not queue
         * failed requests itself; see docs/en/PWA_GUIDE.md.
         */
        'enable_background_sync' => false,
    ],

    /**
     * Icons Configuration
     * Multiple sizes for different devices
     * Generated by: ./sfphp make:pwa --name="..." --logo=path/to/logo.png
     */
    'icons' => [
        [
            'src' => '/assets/icons/icon-192x192.png',
            'sizes' => '192x192',
            'type' => 'image/png',
            'purpose' => 'any',
        ],
        [
            'src' => '/assets/icons/icon-512x512.png',
            'sizes' => '512x512',
            'type' => 'image/png',
            'purpose' => 'any',
        ],
    ],
];

