<?php

namespace SfphpProject\src\Migrations;

use InvalidArgumentException;

/**
 * Collects column definitions for a table schema.
 */
final class Blueprint
{
    /**
     * @var array<int, string>
     */
    private array $columns = [];

    /**
     * Create a blueprint for the given table.
     *
     * @param string $table The table name
     * @param string $driver The PDO driver name
     */
    public function __construct(
        private string $table,
        private string $driver
    ) {}

    /**
     * Add an auto-incrementing identifier column.
     *
     * @param string $name The column name
     * @return self
     */
    public function id(string $name = 'id'): self
    {
        $quoted = $this->quoteIdentifier($name);

        $definition = match ($this->driver) {
            'mysql' => $quoted . ' BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY',
            'pgsql' => $quoted . ' BIGSERIAL PRIMARY KEY',
            'sqlsrv', 'dblib' => $quoted . ' INT IDENTITY(1,1) PRIMARY KEY',
            'sqlite' => $quoted . ' INTEGER PRIMARY KEY AUTOINCREMENT',
            'firebird' => $quoted . ' BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            'oci' => $quoted . ' NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            default => $quoted . ' INTEGER PRIMARY KEY',
        };

        $this->columns[] = $definition;

        return $this;
    }

    /**
     * Add a string column.
     *
     * @param string $name The column name
     * @param int $length The maximum length
     * @return self
     */
    public function string(string $name, int $length = 255): self
    {
        $this->columns[] = $this->quoteIdentifier($name) . ' VARCHAR(' . $length . ') NOT NULL';

        return $this;
    }

    /**
     * Add a text column.
     *
     * @param string $name The column name
     * @return self
     */
    public function text(string $name): self
    {
        $this->columns[] = $this->quoteIdentifier($name) . ' TEXT NOT NULL';

        return $this;
    }

    /**
     * Add an integer column.
     *
     * @param string $name The column name
     * @return self
     */
    public function integer(string $name): self
    {
        $this->columns[] = $this->quoteIdentifier($name) . ' INTEGER NOT NULL';

        return $this;
    }

    /**
     * Add a boolean column.
     *
     * @param string $name The column name
     * @return self
     */
    public function boolean(string $name): self
    {
        $this->columns[] = $this->quoteIdentifier($name) . ' BOOLEAN NOT NULL';

        return $this;
    }

    /**
     * Add created_at and updated_at columns.
     *
     * @return self
     */
    public function timestamps(): self
    {
        $this->columns[] = $this->quoteIdentifier('created_at') . ' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP';
        $this->columns[] = $this->quoteIdentifier('updated_at') . ' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP';

        return $this;
    }

    /**
     * Get the compiled column definitions.
     *
     * @return array<int, string>
     */
    public function compile(): array
    {
        if ($this->columns === []) {
            throw new InvalidArgumentException('A table must contain at least one column.');
        }

        return $this->columns;
    }

    /**
     * Get the table name.
     *
     * @return string
     */
    public function table(): string
    {
        return $this->table;
    }

    /**
     * Quote an identifier for the current driver.
     *
     * @param string $identifier The identifier name
     * @return string
     */
    private function quoteIdentifier(string $identifier): string
    {
        if (!preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $identifier)) {
            throw new InvalidArgumentException("Invalid schema identifier: $identifier");
        }

        return match ($this->driver) {
            'mysql' => '`' . $identifier . '`',
            'sqlsrv', 'dblib' => '[' . $identifier . ']',
            default => '"' . $identifier . '"',
        };
    }
}
