<?php

namespace SfphpProject\src;

use PDO;
use PDOStatement;

/**
 * Executes raw SQL statements with PDO parameter bindings.
 */
class RawQuery
{
    private ?PDOStatement $statement = null;

    /**
     * Create a raw SQL query.
     *
     * @param PDO $pdo The database connection used to execute the query
     * @param string $sql The SQL statement to execute
     * @param array $bindings The named or positional values bound to the statement
     */
    public function __construct(
        private PDO $pdo,
        private string $sql,
        private array $bindings = []
    ) {}

    /**
     * Execute the query and return all matching rows.
     *
     * @return array The matching rows
     */
    public function get(): array
    {
        return $this->execute()->fetchAll();
    }

    /**
     * Execute the query and return the first matching row.
     *
     * @return array|null The first matching row, or null when none is found
     */
    public function first(): ?array
    {
        $result = $this->execute()->fetch();

        return $result === false ? null : $result;
    }

    /**
     * Execute the query and return the first column of the first row.
     *
     * @return mixed The scalar result, or null when none is found
     */
    public function scalar(): mixed
    {
        $result = $this->execute()->fetchColumn();

        return $result === false ? null : $result;
    }

    /**
     * Prepare and execute the raw SQL statement.
     *
     * @return PDOStatement The executed statement
     */
    public function execute(): PDOStatement
    {
        $this->statement = $this->pdo->prepare($this->sql);
        foreach ($this->bindings as $name => $value) {
            $parameter = is_int($name) ? $name + 1 : ':' . ltrim((string) $name, ':');
            $this->statement->bindValue($parameter, $value, $this->pdoType($value));
        }
        $this->statement->execute();

        return $this->statement;
    }

    /**
     * Execute the query and return the number of affected rows.
     *
     * @return int The number of affected rows
     */
    public function rowCount(): int
    {
        return $this->statement?->rowCount() ?? $this->execute()->rowCount();
    }

    /**
     * Execute the query and return its generated identifier.
     *
     * @param string|null $name The sequence name when required by the PDO driver
     * @return string The identifier generated by the database
     */
    public function lastInsertId(?string $name = null): string
    {
        if ($this->statement === null) {
            $this->execute();
        }

        return $this->pdo->lastInsertId($name);
    }

    /**
     * Get the PDO binding type for a value.
     *
     * @param mixed $value The value to bind
     * @return int The matching PDO parameter type
     */
    private function pdoType(mixed $value): int
    {
        return match (true) {
            is_int($value) => PDO::PARAM_INT,
            is_bool($value) => PDO::PARAM_BOOL,
            $value === null => PDO::PARAM_NULL,
            default => PDO::PARAM_STR,
        };
    }
}
